config/routes.rb
Rails.application.routes.draw do
  resources :awsdes
  root "awsdes#index"
  #rootの作成test01
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/awsde.rb
class Awsde < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/awsdes_controller.rb
class AwsdesController < ApplicationController
  before_action :set_awsde, only: [:show, :edit, :update, :destroy]

  # GET /awsdes
  # GET /awsdes.json
  def index
    @awsdes = Awsde.all
  end

  # GET /awsdes/1
  # GET /awsdes/1.json
  def show
  end

  # GET /awsdes/new
  def new
    @awsde = Awsde.new
  end

  # GET /awsdes/1/edit
  def edit
  end

  # POST /awsdes
  # POST /awsdes.json
  def create
    @awsde = Awsde.new(awsde_params)

    respond_to do |format|
      if @awsde.save
        format.html { redirect_to @awsde, notice: 'Awsde was successfully created.' }
        format.json { render :show, status: :created, location: @awsde }
      else
        format.html { render :new }
        format.json { render json: @awsde.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awsdes/1
  # PATCH/PUT /awsdes/1.json
  def update
    respond_to do |format|
      if @awsde.update(awsde_params)
        format.html { redirect_to @awsde, notice: 'Awsde was successfully updated.' }
        format.json { render :show, status: :ok, location: @awsde }
      else
        format.html { render :edit }
        format.json { render json: @awsde.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awsdes/1
  # DELETE /awsdes/1.json
  def destroy
    @awsde.destroy
    respond_to do |format|
      format.html { redirect_to awsdes_url, notice: 'Awsde was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_awsde
      @awsde = Awsde.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def awsde_params
      params.require(:awsde).permit(:title, :context)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awsdes_helper.rb
module AwsdesHelper
end

app/views/awsdes/_form.html.erb
<%= form_with(model: awsde, local: true) do |form| %>
  <% if awsde.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(awsde.errors.count, "error") %> prohibited this awsde from being saved:</h2>

      <ul>
      <% awsde.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :context %>
    <%= form.text_area :context %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/awsdes/edit.html.erb
<h1>Editing Awsde</h1>

<%= render 'form', awsde: @awsde %>

<%= link_to 'Show', @awsde %> |
<%= link_to 'Back', awsdes_path %>

app/views/awsdes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Awsdes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Context</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @awsdes.each do |awsde| %>
      <tr>
        <td><%= awsde.title %></td>
        <td><%= awsde.context %></td>
        <td><%= link_to 'Show', awsde %></td>
        <td><%= link_to 'Edit', edit_awsde_path(awsde) %></td>
        <td><%= link_to 'Destroy', awsde, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Awsde', new_awsde_path %>

app/views/awsdes/new.html.erb
<h1>New Awsde</h1>

<%= render 'form', awsde: @awsde %>

<%= link_to 'Back', awsdes_path %>

app/views/awsdes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @awsde.title %>
</p>

<p>
  <strong>Context:</strong>
  <%= @awsde.context %>
</p>

<%= link_to 'Edit', edit_awsde_path(@awsde) %> |
<%= link_to 'Back', awsdes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awsdep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>